# Inventaire Ansible pour le déploiement local

[all]
localhost ansible_connection=local

[all:vars]
# Variables communes
app_name="Secure Application"
deployment_user=root

# Seulement pour déploiement local
ansible_python_interpreter=/usr/bin/python3
